[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[colors.bright]
black = "#666666"
blue = "#387CD3"
cyan = "#3D97E2"
green = "#77B869"
magenta = "#957BBE"
red = "#E05A4F"
white = "#BABABA"
yellow = "#EFD64B"

[colors.normal]
black = "#000000"
blue = "#1C98E8"
cyan = "#1C98E8"
green = "#68C256"
magenta = "#8E69C9"
red = "#E8341C"
white = "#BABABA"
yellow = "#F2D42C"

[colors.primary]
background = "#222324"
foreground = "#BABABA"

[cursor.style]
shape = "Block"

[font]
size = 12

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.99
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[keyboard]
