# preload = /home/ainur/Images/Wallpapers/2532728.jpg
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used 
# wallpaper = eDP-1,/home/ainur/Images/Wallpapers/2532728.jpg

#fully disable ipc 
# ipc = off

wallpaper {
    monitor = eDP-1
    path = /home/ainur/Images/Wallpapers/
    fit_mode = cover
    timeout = 300
}

splash = false 
